### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by klssmith**
Bumped all of the test and development dependencies. Also bumped some of
the production dependencies, but left the ones where there were major
changes or the changelog couldn't be easily found.

### CODE REVIEW

**Comment by issyl0** [comment]
If you like, we can enable Dependabot?

**Comment by klssmith** [comment]
That would be good, as long as it doesn't start opening PRs too often - maybe we could set it to open monthly PRs.

**Comment by klssmith** [comment]
@issyl0 are you happy for me to merge this for now since I've checked these changelogs, then look into Dependabot after?

**Comment by issyl0** [comment]
Sure. Do whatever! 😄

**Pull request merged**
