### PR TITLE
Add shelves

### PR DESCRIPTION
**Pull request by heathd**
I got fed up of not having records of which books are where, so I've added support for shelves.

Hope this is useful!

## What it does

A shelf can be set for a book when it's not out on loan.

When a book is returned from loan, the shelf is also specified.

A record of the shelf which the book is returned to is kept in the
`loans` table.

(See screenshots)

## Default data

Two shelves will be created by the default migration:

- 'Third floor'
- 'Sixth floor'

(I realise this might be annoying if people outside of GDS are using this app, happy to remove the default data from the migration if that would be preferred).

## Tweaks/cleanups

I also did a few tweaks/cleanups:

- relax ruby version constraint in Gemfile
- remove dependency on capybara-webkit
- allow DB config to be overridden by env vars

And one bugfix:

- if a book isn't found by ISBN search, show a nice error message instead of crashing

### Option to set the shelf for an existing book

screen shot 2017-04-08 at 14 24 31

### Editing the shelf

screen shot 2017-04-08 at 14 24 48

### Returning a book that's on loan

screen shot 2017-04-08 at 14 25 03

### Viewing the loan history

screen shot 2017-04-08 at 14 25 17

### CODE REVIEW

**Comment by issyl0** [comment]
Thanks David, this is very useful! It's a feature I wanted to add at some point, but hadn't got round to it yet.

**Comment by issyl0** [comment]
> (I realise this might be annoying if people outside of GDS are using this app, happy to remove the default data from the migration if that would be preferred).

I don't think anyone outside of GDS is using this fork of it.

**Comment by issyl0** [comment]
I *think* there are some books on 7th too, but I can always add a new migration later when I've worked out whether there are or not! We need to do an audit of all the books anyway, which is something I've delegated that to the learning and development people in the People Team (hence adding CSV export).

**Comment by issyl0** [comment]
I'll merge this on Monday, if that's OK? Then I can test whether it works or not and if so deploy it straight away.

**Comment by heathd** [comment]
> I don't think anyone outside of GDS is using this fork of it.

I saw that there's a fork on `alphagov` as well. I wasn't sure which one is actually in use. Assumed it was your one since it newer commits?

Out of curiosity do you know whether any other organisations have used it?

> I think there are some books on 7th too

yeah, I wasn't sure about that

> I'll merge this on Monday, if that's OK? 

yes, great! No rush!

**Pull request merged**
